/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DynamicForm {
    }
    interface MyForm {
        "age": number;
        "busy": boolean;
        "carBodyStyle": string;
        "counter": number;
        "email": string;
        "favoriteCar": string;
        "fullName": string;
        "hoodScoop": boolean;
        "login": boolean;
        "specialInstructions": string;
        "userName": string;
        "vegetarian": boolean;
        "volume": number;
    }
}
declare global {
    interface HTMLDynamicFormElement extends Components.DynamicForm, HTMLStencilElement {
    }
    var HTMLDynamicFormElement: {
        prototype: HTMLDynamicFormElement;
        new (): HTMLDynamicFormElement;
    };
    interface HTMLMyFormElement extends Components.MyForm, HTMLStencilElement {
    }
    var HTMLMyFormElement: {
        prototype: HTMLMyFormElement;
        new (): HTMLMyFormElement;
    };
    interface HTMLElementTagNameMap {
        "dynamic-form": HTMLDynamicFormElement;
        "my-form": HTMLMyFormElement;
    }
}
declare namespace LocalJSX {
    interface DynamicForm {
    }
    interface MyForm {
        "age"?: number;
        "busy"?: boolean;
        "carBodyStyle"?: string;
        "counter"?: number;
        "email"?: string;
        "favoriteCar"?: string;
        "fullName"?: string;
        "hoodScoop"?: boolean;
        "login"?: boolean;
        "specialInstructions"?: string;
        "userName"?: string;
        "vegetarian"?: boolean;
        "volume"?: number;
    }
    interface IntrinsicElements {
        "dynamic-form": DynamicForm;
        "my-form": MyForm;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dynamic-form": LocalJSX.DynamicForm & JSXBase.HTMLAttributes<HTMLDynamicFormElement>;
            "my-form": LocalJSX.MyForm & JSXBase.HTMLAttributes<HTMLMyFormElement>;
        }
    }
}
